### ISSUE TITLE
基本構造の構築

### ISSUE THREAD

**Issue by susatthi** [team-musashi/stamp-rally#3]
# 要件

- Welcome 画面の作成
  - 未ログインの場合に表示する
  - 「はじめる」ボタンがあり、ボタン押下で匿名認証してFirestoreにuserドキュメントを作成してホーム画面に遷移する
- Home 画面の作成
  - ログイン済みの場合に表示する
  - 「ユーザー削除」ボタンがあり、ボタン押下で認証ユーザーを削除して Welcome 画面に遷移する

# TODO（アプリ）
- [x] デフォルトブランチを develop に切り替える
- [x] fvm の導入
- [x] Makefile の導入
- [x] vscode設定
- [x] GitHub ISSUEテンプレートの追加
- [x] GitHub PRテンプレートの追加
- [x] コミットテンプレートの追加
- [x] pedantic_mono（linter）を導入
- [x] ロガー（roggle）を導入
- [x] iOSにinvertaseのSDKを追加（ビルド時間短縮）
- [x] 匿名認証でログイン機能を実装
- [x] 認証ユーザーの削除機能を実装
- [x] READMEに、ビルド方法、ブランチモデル、各コマンドについて書く

firebaseのほうは
https://github.com/team-musashi/stamp-rally-firebase/issues/1
でやる

**Comment by susatthi** [comment]
完了したのでクローズ！
